### PR TITLE
Product page

### PR DESCRIPTION
**Pull request by SRUJANA-PENUGONDA13**
## Added Filter functionality for product listing page

### CODE REVIEW

**Review by anshtripathi01 — APPROVED** [review]
Code , file structure and ui looks good clean Good to merge

**Review by anjali1102 — APPROVED** [review]

**Comment by SRUJANA-PENUGONDA13** [comment]
Thank You @anshtripathi01 @anjali1102 for review

**Review by amirnathani9 — COMMENTED** [review]
clean code practices followed
good folder structure
good to merge

**Comment by anjali1102** [comment]
we can do barell export
filter css , color variable is messy a bit
functionality working nicely
Great efforts

**Pull request merged**
